# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: AaveV3 Indexer
description: Aave V3 Indexer for Envio
ecosystem: evm

contracts:
  - name: AaveOracle
    abi_file_path: ./src/abis/v3/AaveOracle.json
    handler: ./src/eventHandlers/oracleHandlers.ts
    events:
      - event: AssetSourceUpdated(address indexed asset, address indexed source)
      - event: FallbackOracleUpdated(address fallbackOracle)
      - event: BaseCurrencySet(address baseCurrency, uint256 baseUnit)

networks:
  - id: 8453 # Example network (Base mainnet)
    start_block: 2357113
    contracts:
      - name: AaveOracle
        address: "0x2Cc0Fc26eD4563A5ce5e8bdcfe1A2878676Ae156" # Replace with actual contract address

field_selection:
  transaction_fields:
    - "hash"
    - "gasUsed"
  block_fields:
    - "parentHash"
    - "gasUsed"
    - "miner"
